name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - os: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }} .

    - name: Create archive
      run: |
        if [ "${{ matrix.os }}" = "linux" ]; then
          tar -czf mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}.tar.gz mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}
        else
          tar -czf mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}.tar.gz mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}
        path: mcp-terminal-server-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -la artifacts/
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*/mcp-terminal-server-*.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}